id = "icons-themes"
name = "Icons Themes"
version = "0.0.1"
schema_version = 1
authors = ["DvAndresGT <diegogiraldo506@gmail.com>"]
description = "Default icon themes for zed variety to choose from."
repository = "https://github.com/AndresGT/material-icon-theme-zed"
